# Generated by Django 5.1.3 on 2024-12-04 06:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_matchmakingqueue'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchmakingqueue',
            name='time_limit',
            field=models.DurationField(default=datetime.timedelta(days=1)),
        ),
    ]
