# Generated by Django 5.1.3 on 2024-12-04 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_matchmakingqueue_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='points',
            new_name='computer_points',
        ),
        migrations.AddField(
            model_name='customuser',
            name='online_rating',
            field=models.PositiveIntegerField(default=1000),
        ),
    ]
